export type ProductCategory =
  | "Cakes"
  | "Pastries"
  | "Bread"
  | "Cookies"
  | "Cupcakes"
  | "Drinks";

export type Product = {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  rating: number;
  description: string;
  ingredients: string[];
  allergens: string[];
  image: string;
  badge?: string;
};

export const categories: ProductCategory[] = [
  "Cakes",
  "Pastries",
  "Bread",
  "Cookies",
  "Cupcakes",
  "Drinks",
];

export const products: Product[] = [
  {
    id: "chocolate-fudge-cake",
    name: "Chocolate Fudge Cake",
    category: "Cakes",
    price: 32,
    rating: 4.9,
    description: "Deep cocoa layers, silky ganache, and a little sea salt.",
    ingredients: ["Belgian chocolate", "Cultured butter", "Free-range eggs", "Cane sugar"],
    allergens: ["Wheat", "Eggs", "Milk", "Soy"],
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85",
    badge: "Bestseller",
  },
  {
    id: "strawberry-cream-cake",
    name: "Strawberry Cream Cake",
    category: "Cakes",
    price: 35,
    rating: 4.8,
    description: "Vanilla sponge, cloud-soft cream, and fresh local berries.",
    ingredients: ["Fresh strawberries", "Vanilla", "Whipping cream", "Free-range eggs"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "red-velvet-cake",
    name: "Red Velvet Cake",
    category: "Cakes",
    price: 34,
    rating: 4.8,
    description: "A tender cocoa crumb with tangy cream cheese frosting.",
    ingredients: ["Cocoa", "Buttermilk", "Cream cheese", "Vanilla"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "vanilla-celebration-cake",
    name: "Vanilla Celebration Cake",
    category: "Cakes",
    price: 30,
    rating: 4.7,
    description: "Our classic vanilla buttercream cake, ready for any little occasion.",
    ingredients: ["Madagascar vanilla", "Cultured butter", "Cane sugar"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1557979619-445218f326b9?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "strawberry-cheesecake",
    name: "Strawberry Cheesecake",
    category: "Cakes",
    price: 7.5,
    rating: 4.9,
    description: "Creamy baked cheesecake on a buttery biscuit base.",
    ingredients: ["Cream cheese", "Strawberries", "Digestive biscuit", "Vanilla"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "chocolate-croissant",
    name: "Chocolate Croissant",
    category: "Pastries",
    price: 4.5,
    rating: 4.9,
    description: "Flaky, hand-laminated pastry wrapped around dark chocolate.",
    ingredients: ["European butter", "Dark chocolate", "Unbleached flour"],
    allergens: ["Wheat", "Milk", "Eggs", "Soy"],
    image: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=900&q=85",
    badge: "Bestseller",
  },
  {
    id: "almond-croissant",
    name: "Almond Croissant",
    category: "Pastries",
    price: 5,
    rating: 4.8,
    description: "Twice-baked with almond cream and toasted flaked almonds.",
    ingredients: ["Almonds", "European butter", "Vanilla", "Unbleached flour"],
    allergens: ["Wheat", "Milk", "Eggs", "Tree nuts"],
    image: "https://images.unsplash.com/photo-1623334044303-241021148842?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "cinnamon-roll",
    name: "Cinnamon Roll",
    category: "Pastries",
    price: 4,
    rating: 4.9,
    description: "Soft swirls with fragrant cinnamon sugar and vanilla glaze.",
    ingredients: ["Ceylon cinnamon", "Cultured butter", "Vanilla"],
    allergens: ["Wheat", "Milk", "Eggs"],
    image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=900&q=85",
    badge: "Bestseller",
  },
  {
    id: "apple-danish",
    name: "Apple Danish",
    category: "Pastries",
    price: 4.25,
    rating: 4.7,
    description: "Buttery pastry with slow-cooked orchard apple and a hint of cardamom.",
    ingredients: ["Orchard apples", "Cardamom", "European butter"],
    allergens: ["Wheat", "Milk", "Eggs"],
    image: "https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "sourdough-bread",
    name: "Sourdough Bread",
    category: "Bread",
    price: 7,
    rating: 4.9,
    description: "Naturally leavened for 36 hours with a crisp, golden crust.",
    ingredients: ["Unbleached flour", "Filtered water", "Sea salt", "Sourdough culture"],
    allergens: ["Wheat"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85",
    badge: "Bestseller",
  },
  {
    id: "french-baguette",
    name: "French Baguette",
    category: "Bread",
    price: 5,
    rating: 4.7,
    description: "A crisp, airy Parisian-style loaf baked fresh each morning.",
    ingredients: ["Unbleached flour", "Filtered water", "Sea salt", "Yeast"],
    allergens: ["Wheat"],
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "multigrain-bread",
    name: "Multigrain Bread",
    category: "Bread",
    price: 6.5,
    rating: 4.7,
    description: "A hearty, seeded loaf with a soft crumb and toasted edges.",
    ingredients: ["Whole wheat", "Sunflower seeds", "Pumpkin seeds", "Oats"],
    allergens: ["Wheat", "Sesame"],
    image: "https://images.unsplash.com/photo-1534620808146-d33bb39128b2?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "chocolate-chip-cookie",
    name: "Chocolate Chip Cookie",
    category: "Cookies",
    price: 2.5,
    rating: 4.8,
    description: "Crisp at the edges, chewy in the middle, and generously dotted.",
    ingredients: ["Dark chocolate", "Cultured butter", "Brown sugar", "Vanilla"],
    allergens: ["Wheat", "Eggs", "Milk", "Soy"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "double-chocolate-cookie",
    name: "Double Chocolate Cookie",
    category: "Cookies",
    price: 3,
    rating: 4.8,
    description: "A fudgy cocoa cookie with pockets of dark chocolate.",
    ingredients: ["Cocoa", "Dark chocolate", "Brown sugar", "Vanilla"],
    allergens: ["Wheat", "Eggs", "Milk", "Soy"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "oatmeal-raisin-cookie",
    name: "Oatmeal Raisin Cookie",
    category: "Cookies",
    price: 2.5,
    rating: 4.7,
    description: "Rolled oats, plump raisins, and a cozy touch of cinnamon.",
    ingredients: ["Rolled oats", "Raisins", "Ceylon cinnamon", "Brown sugar"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "vanilla-cupcake",
    name: "Vanilla Cupcake",
    category: "Cupcakes",
    price: 3,
    rating: 4.7,
    description: "Light vanilla sponge topped with a swirl of buttercream.",
    ingredients: ["Madagascar vanilla", "Cultured butter", "Free-range eggs"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "chocolate-cupcake",
    name: "Chocolate Cupcake",
    category: "Cupcakes",
    price: 3,
    rating: 4.8,
    description: "Rich chocolate sponge finished with whipped ganache.",
    ingredients: ["Belgian chocolate", "Cocoa", "Cultured butter"],
    allergens: ["Wheat", "Eggs", "Milk", "Soy"],
    image: "https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "red-velvet-cupcake",
    name: "Red Velvet Cupcake",
    category: "Cupcakes",
    price: 3.5,
    rating: 4.8,
    description: "A little red velvet classic with a cream cheese crown.",
    ingredients: ["Cocoa", "Buttermilk", "Cream cheese", "Vanilla"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "cappuccino",
    name: "Cappuccino",
    category: "Drinks",
    price: 4,
    rating: 4.8,
    description: "A double shot of house espresso under velvety steamed milk.",
    ingredients: ["House espresso", "Whole milk"],
    allergens: ["Milk"],
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "iced-latte",
    name: "Iced Latte",
    category: "Drinks",
    price: 4.5,
    rating: 4.7,
    description: "Chilled espresso and fresh milk poured over plenty of ice.",
    ingredients: ["House espresso", "Whole milk", "Ice"],
    allergens: ["Milk"],
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    category: "Drinks",
    price: 4,
    rating: 4.9,
    description: "A warming cup of slow-melted chocolate and steamed milk.",
    ingredients: ["Belgian chocolate", "Whole milk", "Cocoa"],
    allergens: ["Milk", "Soy"],
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "blueberry-muffin",
    name: "Blueberry Muffin",
    category: "Pastries",
    price: 3.75,
    rating: 4.8,
    description: "A soft, buttery muffin bursting with juicy blueberries.",
    ingredients: ["Blueberries", "Cultured butter", "Lemon zest", "Vanilla"],
    allergens: ["Wheat", "Eggs", "Milk"],
    image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?auto=format&fit=crop&w=900&q=85",
  },
];

export function findProduct(id: string) {
  return products.find((product) => product.id === id);
}