import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Heart, Leaf, Wheat } from "lucide-react";

const gallery = [
  ["https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=85", "Flaky morning pastries cooling on the counter"],
  ["https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=900&q=85", "Baker shaping fresh dough by hand"],
  ["https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=85", "Golden country loaves ready for the day"],
  ["https://images.unsplash.com/photo-1530610476181-d83430b64dcd?auto=format&fit=crop&w=900&q=85", "A just-baked chocolate croissant"],
];

export default function AboutPage() {
  return <>
    <section className="about-hero"><div className="about-hero-copy"><span className="eyebrow">A neighborhood kind of story</span><h1>Good things<br/>take <em>time.</em></h1><p>And the best ones are made together. This is the story of a little bakery that grew around a shared table.</p><span className="about-signature">With love, from our kitchen <span>✳</span></span></div><div className="about-hero-image"><Image src="https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1400&q=85" alt="A baker shaping dough in a sunlit bakery kitchen" fill priority sizes="(max-width: 760px) 100vw, 58vw" unoptimized/><span className="image-caption">Our kitchen, just before the day begins</span></div></section>

    <section className="story-intro-section"><div className="story-intro-label"><span className="eyebrow">How it began</span><span className="story-year">2014 — today</span></div><div className="story-intro-main"><h2>It started with a simple dream: to make something <em>worth slowing down for.</em></h2><p>Sweet Crust Bakery started with a simple dream: to create delicious baked goods using traditional techniques, quality ingredients, and a little extra love. Today, we bake fresh every morning for our local community.</p><p>Our first oven was second-hand, the kitchen was tiny, and our sourdough starter had a name (Mabel, naturally). What we lacked in space, we made up for with patience. A dozen years later, we still begin the same way: sleeves rolled up, ovens warming, and the first batch of dough resting beneath a tea towel.</p><Link className="text-link" href="/menu">Meet today’s bakes <ArrowRight size={15}/></Link></div></section>

    <section className="founder-section"><div className="founder-image"><Image src="https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=1000&q=85" alt="Founder and head baker Lena Martin in her kitchen" fill sizes="(max-width: 760px) 100vw, 46vw" unoptimized/><span className="founder-caption">Lena Martin · Founder & Head Baker</span></div><div className="founder-copy"><span className="eyebrow">A note from Lena</span><blockquote>“I wanted to make the kind of bread that brought people to the kitchen before it even hit the table.”</blockquote><p>That still happens most mornings. You can smell the first loaves from the sidewalk, and someone always wanders in to ask what’s just come out of the oven. That’s the good part. The bakery has grown, but the feeling we’re chasing is still the same: warm, welcome, and a little bit wonderful.</p><span className="founder-sign">Lena <span>✳</span></span></div></section>

    <section className="values-section"><div className="values-heading"><span className="eyebrow">What we believe</span><h2>Goodness, <em>by design.</em></h2></div><div className="values-list"><article><span className="value-icon"><Wheat/></span><div><h3>Respect the process</h3><p>Time is our most important ingredient. Dough gets the rest it needs; flavors get room to become themselves.</p></div><span className="value-index">01</span></article><article><span className="value-icon"><Leaf/></span><div><h3>Choose with care</h3><p>We work with small growers and makers who care as much about their ingredients as we do about what we make with them.</p></div><span className="value-index">02</span></article><article><span className="value-icon"><Heart/></span><div><h3>Make room for everyone</h3><p>A bakery belongs to the whole neighborhood. We bake for celebrations, everyday rituals, and everyone at the table.</p></div><span className="value-index">03</span></article></div></section>

    <section className="process-section"><div className="process-image"><Image src="https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=1200&q=85" alt="Fresh loaves cooling on a wooden bakery rack" fill sizes="(max-width: 760px) 100vw, 50vw" unoptimized/><span className="image-caption">The quiet moment before the doors open</span></div><div className="process-copy"><span className="eyebrow">From scratch, each day</span><h2>Our baking <em>rhythm.</em></h2><div className="process-steps"><article><span>04:30</span><div><h3>The first light</h3><p>Our bakers arrive while Maple Street is still quiet. The ovens go on, the dough comes out.</p></div></article><article><span>06:00</span><div><h3>Hands in the dough</h3><p>Loaves are scored, pastries shaped, and cakes layered by people who know their craft.</p></div></article><article><span>08:00</span><div><h3>Doors open, coffee on</h3><p>The first tray reaches the counter just in time for your morning walk.</p></div></article></div></div></section>

    <section className="team-section section"><div className="section-heading-row"><div><span className="eyebrow">Good hands, good hearts</span><h2>Meet the <em>makers.</em></h2></div><p>Small team, shared apron hooks, very strong opinions about cinnamon.</p></div><div className="team-grid"><article><div className="team-photo"><Image src="https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=700&q=85" alt="Lena, founder and head baker" fill sizes="30vw" unoptimized/></div><h3>Lena Martin</h3><p>Founder & Head Baker</p></article><article><div className="team-photo"><Image src="https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=700&q=85" alt="Marco preparing pastries in the bakery kitchen" fill sizes="30vw" unoptimized/></div><h3>Marco Alvarez</h3><p>Pastry Lead</p></article><article><div className="team-photo"><Image src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85" alt="Nia welcoming a customer at the bakery counter" fill sizes="30vw" unoptimized/></div><h3>Nia Brooks</h3><p>Counter & Coffee</p></article></div></section>

    <section className="gallery-section"><div className="section-heading-row"><div><span className="eyebrow">Little moments from our kitchen</span><h2>In good <em>company.</em></h2></div><span className="gallery-handle">@sweetcrustbakery <ArrowUpRight size={15}/></span></div><div className="story-gallery">{gallery.map(([src, alt], index) => <div className={`gallery-photo gallery-photo-${index + 1}`} key={src}><Image src={src} alt={alt} fill sizes="(max-width: 760px) 48vw, 25vw" unoptimized/></div>)}</div></section>

    <section className="about-cta"><span className="eyebrow">Save a seat for us</span><h2>Come by. We’ll put<br/><em>the kettle on.</em></h2><Link className="button button-dark" href="/contact">Visit our bakery <ArrowUpRight size={15}/></Link></section>
  </>;
}